# Generated by Django 5.0.4 on 2025-01-27 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Defi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "difficulte",
                    models.CharField(
                        choices=[
                            ("facile", "Facile"),
                            ("moyen", "Moyen"),
                            ("difficile", "Difficile"),
                        ],
                        max_length=50,
                    ),
                ),
                ("points", models.PositiveIntegerField()),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("Debutant", "Débutant"),
                            ("Intermediaire", "Intermédiaire"),
                            ("Avance", "Avancé"),
                        ],
                        max_length=50,
                    ),
                ),
                ("flag", models.CharField(max_length=255)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Soumission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flag_soumis", models.CharField(max_length=255)),
                ("date_soumission", models.DateTimeField(auto_now_add=True)),
                ("est_correct", models.BooleanField(default=False)),
                (
                    "defi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.defi"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.user"
                    ),
                ),
            ],
        ),
    ]
